// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: realworld/v1/article.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReply) Reset() {
	*x = ProfileReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReply) ProtoMessage() {}

func (x *ProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReply.ProtoReflect.Descriptor instead.
func (*ProfileReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileReply) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileReply) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProfileReply) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type MultipleArticlesReply struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Articles      []*MultipleArticlesReply_Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	ArticlesCount uint64                           `protobuf:"varint,2,opt,name=articlesCount,proto3" json:"articlesCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleArticlesReply) Reset() {
	*x = MultipleArticlesReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleArticlesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleArticlesReply) ProtoMessage() {}

func (x *MultipleArticlesReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleArticlesReply.ProtoReflect.Descriptor instead.
func (*MultipleArticlesReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{1}
}

func (x *MultipleArticlesReply) GetArticles() []*MultipleArticlesReply_Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *MultipleArticlesReply) GetArticlesCount() uint64 {
	if x != nil {
		return x.ArticlesCount
	}
	return 0
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Article       *CreateArticleRequest_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_realworld_v1_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleRequest) GetArticle() *CreateArticleRequest_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type SingleArticleReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slug           string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Body           string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TagList        []string               `protobuf:"bytes,5,rep,name=tagList,proto3" json:"tagList,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Favorited      string                 `protobuf:"bytes,8,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoritesCount uint64                 `protobuf:"varint,9,opt,name=favoritesCount,proto3" json:"favoritesCount,omitempty"`
	Author         *ProfileReply          `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SingleArticleReply) Reset() {
	*x = SingleArticleReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleArticleReply) ProtoMessage() {}

func (x *SingleArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleArticleReply.ProtoReflect.Descriptor instead.
func (*SingleArticleReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{3}
}

func (x *SingleArticleReply) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SingleArticleReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SingleArticleReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SingleArticleReply) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SingleArticleReply) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *SingleArticleReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SingleArticleReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SingleArticleReply) GetFavorited() string {
	if x != nil {
		return x.Favorited
	}
	return ""
}

func (x *SingleArticleReply) GetFavoritesCount() uint64 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

func (x *SingleArticleReply) GetAuthor() *ProfileReply {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleReply) Reset() {
	*x = CreateArticleReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReply) ProtoMessage() {}

func (x *CreateArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReply.ProtoReflect.Descriptor instead.
func (*CreateArticleReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{4}
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Article       *UpdateArticleRequest_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Slug          string                        `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_realworld_v1_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateArticleRequest) GetArticle() *UpdateArticleRequest_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *UpdateArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type UpdateArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleReply) Reset() {
	*x = UpdateArticleReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReply) ProtoMessage() {}

func (x *UpdateArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReply.ProtoReflect.Descriptor instead.
func (*UpdateArticleReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{6}
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_realworld_v1_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type DeleteArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReply) Reset() {
	*x = DeleteArticleReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReply) ProtoMessage() {}

func (x *DeleteArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReply.ProtoReflect.Descriptor instead.
func (*DeleteArticleReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{8}
}

type GetArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesRequest) Reset() {
	*x = GetArticlesRequest{}
	mi := &file_realworld_v1_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesRequest) ProtoMessage() {}

func (x *GetArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetArticlesRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{9}
}

func (x *GetArticlesRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetArticlesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesReply) Reset() {
	*x = GetArticlesReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesReply) ProtoMessage() {}

func (x *GetArticlesReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesReply.ProtoReflect.Descriptor instead.
func (*GetArticlesReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{10}
}

type ListArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Favorited     string                 `protobuf:"bytes,3,opt,name=favorited,proto3" json:"favorited,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleRequest) Reset() {
	*x = ListArticleRequest{}
	mi := &file_realworld_v1_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleRequest) ProtoMessage() {}

func (x *ListArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleRequest.ProtoReflect.Descriptor instead.
func (*ListArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{11}
}

func (x *ListArticleRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListArticleRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListArticleRequest) GetFavorited() string {
	if x != nil {
		return x.Favorited
	}
	return ""
}

func (x *ListArticleRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArticleRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleReply) Reset() {
	*x = ListArticleReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleReply) ProtoMessage() {}

func (x *ListArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleReply.ProtoReflect.Descriptor instead.
func (*ListArticleReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{12}
}

type FeedArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedArticleRequest) Reset() {
	*x = FeedArticleRequest{}
	mi := &file_realworld_v1_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedArticleRequest) ProtoMessage() {}

func (x *FeedArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedArticleRequest.ProtoReflect.Descriptor instead.
func (*FeedArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{13}
}

func (x *FeedArticleRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FeedArticleRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FeedArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedArticleReply) Reset() {
	*x = FeedArticleReply{}
	mi := &file_realworld_v1_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedArticleReply) ProtoMessage() {}

func (x *FeedArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedArticleReply.ProtoReflect.Descriptor instead.
func (*FeedArticleReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{14}
}

type FavoriteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteArticleRequest) Reset() {
	*x = FavoriteArticleRequest{}
	mi := &file_realworld_v1_article_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteArticleRequest) ProtoMessage() {}

func (x *FavoriteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteArticleRequest.ProtoReflect.Descriptor instead.
func (*FavoriteArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{15}
}

func (x *FavoriteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type UnfavoriteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteArticleRequest) Reset() {
	*x = UnfavoriteArticleRequest{}
	mi := &file_realworld_v1_article_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteArticleRequest) ProtoMessage() {}

func (x *UnfavoriteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteArticleRequest.ProtoReflect.Descriptor instead.
func (*UnfavoriteArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{16}
}

func (x *UnfavoriteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type MultipleArticlesReply_Article struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slug           string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TagList        []string               `protobuf:"bytes,4,rep,name=tagList,proto3" json:"tagList,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Favorited      bool                   `protobuf:"varint,7,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoritesCount uint64                 `protobuf:"varint,8,opt,name=favoritesCount,proto3" json:"favoritesCount,omitempty"`
	Author         *ProfileReply          `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultipleArticlesReply_Article) Reset() {
	*x = MultipleArticlesReply_Article{}
	mi := &file_realworld_v1_article_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleArticlesReply_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleArticlesReply_Article) ProtoMessage() {}

func (x *MultipleArticlesReply_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleArticlesReply_Article.ProtoReflect.Descriptor instead.
func (*MultipleArticlesReply_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MultipleArticlesReply_Article) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MultipleArticlesReply_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MultipleArticlesReply_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MultipleArticlesReply_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *MultipleArticlesReply_Article) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MultipleArticlesReply_Article) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MultipleArticlesReply_Article) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

func (x *MultipleArticlesReply_Article) GetFavoritesCount() uint64 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

func (x *MultipleArticlesReply_Article) GetAuthor() *ProfileReply {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateArticleRequest_Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TagList       []string               `protobuf:"bytes,4,rep,name=tagList,proto3" json:"tagList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest_Article) Reset() {
	*x = CreateArticleRequest_Article{}
	mi := &file_realworld_v1_article_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest_Article) ProtoMessage() {}

func (x *CreateArticleRequest_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest_Article.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateArticleRequest_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

type UpdateArticleRequest_Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TagList       []string               `protobuf:"bytes,4,rep,name=tagList,proto3" json:"tagList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest_Article) Reset() {
	*x = UpdateArticleRequest_Article{}
	mi := &file_realworld_v1_article_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest_Article) ProtoMessage() {}

func (x *UpdateArticleRequest_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_article_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest_Article.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_article_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpdateArticleRequest_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateArticleRequest_Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UpdateArticleRequest_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

var File_realworld_v1_article_proto protoreflect.FileDescriptor

const file_realworld_v1_article_proto_rawDesc = "" +
	"\n" +
	"\x1arealworld/v1/article.proto\x12\x10api.realworld.v1\x1a\x1cgoogle/api/annotations.proto\"p\n" +
	"\fProfileReply\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\"\xb6\x03\n" +
	"\x15MultipleArticlesReply\x12K\n" +
	"\barticles\x18\x01 \x03(\v2/.api.realworld.v1.MultipleArticlesReply.ArticleR\barticles\x12$\n" +
	"\rarticlesCount\x18\x02 \x01(\x04R\rarticlesCount\x1a\xa9\x02\n" +
	"\aArticle\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\atagList\x18\x04 \x03(\tR\atagList\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\x12\x1c\n" +
	"\tfavorited\x18\a \x01(\bR\tfavorited\x12&\n" +
	"\x0efavoritesCount\x18\b \x01(\x04R\x0efavoritesCount\x126\n" +
	"\x06author\x18\t \x01(\v2\x1e.api.realworld.v1.ProfileReplyR\x06author\"\xd1\x01\n" +
	"\x14CreateArticleRequest\x12H\n" +
	"\aarticle\x18\x01 \x01(\v2..api.realworld.v1.CreateArticleRequest.ArticleR\aarticle\x1ao\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x18\n" +
	"\atagList\x18\x04 \x03(\tR\atagList\"\xc8\x02\n" +
	"\x12SingleArticleReply\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x18\n" +
	"\atagList\x18\x05 \x03(\tR\atagList\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\tR\tupdatedAt\x12\x1c\n" +
	"\tfavorited\x18\b \x01(\tR\tfavorited\x12&\n" +
	"\x0efavoritesCount\x18\t \x01(\x04R\x0efavoritesCount\x126\n" +
	"\x06author\x18\n" +
	" \x01(\v2\x1e.api.realworld.v1.ProfileReplyR\x06author\"\x14\n" +
	"\x12CreateArticleReply\"\xe5\x01\n" +
	"\x14UpdateArticleRequest\x12H\n" +
	"\aarticle\x18\x01 \x01(\v2..api.realworld.v1.UpdateArticleRequest.ArticleR\aarticle\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x1ao\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x18\n" +
	"\atagList\x18\x04 \x03(\tR\atagList\"\x14\n" +
	"\x12UpdateArticleReply\"*\n" +
	"\x14DeleteArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x14\n" +
	"\x12DeleteArticleReply\"(\n" +
	"\x12GetArticlesRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x12\n" +
	"\x10GetArticlesReply\"\x8a\x01\n" +
	"\x12ListArticleRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1c\n" +
	"\tfavorited\x18\x03 \x01(\tR\tfavorited\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x04R\x06offset\"\x12\n" +
	"\x10ListArticleReply\"B\n" +
	"\x12FeedArticleRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x12\n" +
	"\x10FeedArticleReply\",\n" +
	"\x16FavoriteArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\".\n" +
	"\x18UnfavoriteArticleRequest\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug2\x83\b\n" +
	"\aArticle\x12w\n" +
	"\rCreateArticle\x12&.api.realworld.v1.CreateArticleRequest\x1a$.api.realworld.v1.SingleArticleReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/articles\x12~\n" +
	"\rUpdateArticle\x12&.api.realworld.v1.UpdateArticleRequest\x1a$.api.realworld.v1.SingleArticleReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/articles/{slug}\x12{\n" +
	"\rDeleteArticle\x12&.api.realworld.v1.DeleteArticleRequest\x1a$.api.realworld.v1.SingleArticleReply\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/articles/{slug}\x12u\n" +
	"\vGetArticles\x12$.api.realworld.v1.GetArticlesRequest\x1a\".api.realworld.v1.GetArticlesReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/articles/{slug}\x12s\n" +
	"\vListArticle\x12$.api.realworld.v1.ListArticleRequest\x1a'.api.realworld.v1.MultipleArticlesReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/articles\x12y\n" +
	"\fFeedArticles\x12$.api.realworld.v1.FeedArticleRequest\x1a'.api.realworld.v1.MultipleArticlesReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/articles/feed\x12\x8b\x01\n" +
	"\x0fFavoriteArticle\x12(.api.realworld.v1.FavoriteArticleRequest\x1a$.api.realworld.v1.SingleArticleReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/articles/{slug}/favorite\x12\x8c\x01\n" +
	"\x11UnfavoriteArticle\x12*.api.realworld.v1.UnfavoriteArticleRequest\x1a$.api.realworld.v1.SingleArticleReply\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/articles/{slug}/favoriteB&Z$kratos-realworld/api/realworld/v1;v1b\x06proto3"

var (
	file_realworld_v1_article_proto_rawDescOnce sync.Once
	file_realworld_v1_article_proto_rawDescData []byte
)

func file_realworld_v1_article_proto_rawDescGZIP() []byte {
	file_realworld_v1_article_proto_rawDescOnce.Do(func() {
		file_realworld_v1_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realworld_v1_article_proto_rawDesc), len(file_realworld_v1_article_proto_rawDesc)))
	})
	return file_realworld_v1_article_proto_rawDescData
}

var file_realworld_v1_article_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_realworld_v1_article_proto_goTypes = []any{
	(*ProfileReply)(nil),                  // 0: api.realworld.v1.ProfileReply
	(*MultipleArticlesReply)(nil),         // 1: api.realworld.v1.MultipleArticlesReply
	(*CreateArticleRequest)(nil),          // 2: api.realworld.v1.CreateArticleRequest
	(*SingleArticleReply)(nil),            // 3: api.realworld.v1.SingleArticleReply
	(*CreateArticleReply)(nil),            // 4: api.realworld.v1.CreateArticleReply
	(*UpdateArticleRequest)(nil),          // 5: api.realworld.v1.UpdateArticleRequest
	(*UpdateArticleReply)(nil),            // 6: api.realworld.v1.UpdateArticleReply
	(*DeleteArticleRequest)(nil),          // 7: api.realworld.v1.DeleteArticleRequest
	(*DeleteArticleReply)(nil),            // 8: api.realworld.v1.DeleteArticleReply
	(*GetArticlesRequest)(nil),            // 9: api.realworld.v1.GetArticlesRequest
	(*GetArticlesReply)(nil),              // 10: api.realworld.v1.GetArticlesReply
	(*ListArticleRequest)(nil),            // 11: api.realworld.v1.ListArticleRequest
	(*ListArticleReply)(nil),              // 12: api.realworld.v1.ListArticleReply
	(*FeedArticleRequest)(nil),            // 13: api.realworld.v1.FeedArticleRequest
	(*FeedArticleReply)(nil),              // 14: api.realworld.v1.FeedArticleReply
	(*FavoriteArticleRequest)(nil),        // 15: api.realworld.v1.FavoriteArticleRequest
	(*UnfavoriteArticleRequest)(nil),      // 16: api.realworld.v1.UnfavoriteArticleRequest
	(*MultipleArticlesReply_Article)(nil), // 17: api.realworld.v1.MultipleArticlesReply.Article
	(*CreateArticleRequest_Article)(nil),  // 18: api.realworld.v1.CreateArticleRequest.Article
	(*UpdateArticleRequest_Article)(nil),  // 19: api.realworld.v1.UpdateArticleRequest.Article
}
var file_realworld_v1_article_proto_depIdxs = []int32{
	17, // 0: api.realworld.v1.MultipleArticlesReply.articles:type_name -> api.realworld.v1.MultipleArticlesReply.Article
	18, // 1: api.realworld.v1.CreateArticleRequest.article:type_name -> api.realworld.v1.CreateArticleRequest.Article
	0,  // 2: api.realworld.v1.SingleArticleReply.author:type_name -> api.realworld.v1.ProfileReply
	19, // 3: api.realworld.v1.UpdateArticleRequest.article:type_name -> api.realworld.v1.UpdateArticleRequest.Article
	0,  // 4: api.realworld.v1.MultipleArticlesReply.Article.author:type_name -> api.realworld.v1.ProfileReply
	2,  // 5: api.realworld.v1.Article.CreateArticle:input_type -> api.realworld.v1.CreateArticleRequest
	5,  // 6: api.realworld.v1.Article.UpdateArticle:input_type -> api.realworld.v1.UpdateArticleRequest
	7,  // 7: api.realworld.v1.Article.DeleteArticle:input_type -> api.realworld.v1.DeleteArticleRequest
	9,  // 8: api.realworld.v1.Article.GetArticles:input_type -> api.realworld.v1.GetArticlesRequest
	11, // 9: api.realworld.v1.Article.ListArticle:input_type -> api.realworld.v1.ListArticleRequest
	13, // 10: api.realworld.v1.Article.FeedArticles:input_type -> api.realworld.v1.FeedArticleRequest
	15, // 11: api.realworld.v1.Article.FavoriteArticle:input_type -> api.realworld.v1.FavoriteArticleRequest
	16, // 12: api.realworld.v1.Article.UnfavoriteArticle:input_type -> api.realworld.v1.UnfavoriteArticleRequest
	3,  // 13: api.realworld.v1.Article.CreateArticle:output_type -> api.realworld.v1.SingleArticleReply
	3,  // 14: api.realworld.v1.Article.UpdateArticle:output_type -> api.realworld.v1.SingleArticleReply
	3,  // 15: api.realworld.v1.Article.DeleteArticle:output_type -> api.realworld.v1.SingleArticleReply
	10, // 16: api.realworld.v1.Article.GetArticles:output_type -> api.realworld.v1.GetArticlesReply
	1,  // 17: api.realworld.v1.Article.ListArticle:output_type -> api.realworld.v1.MultipleArticlesReply
	1,  // 18: api.realworld.v1.Article.FeedArticles:output_type -> api.realworld.v1.MultipleArticlesReply
	3,  // 19: api.realworld.v1.Article.FavoriteArticle:output_type -> api.realworld.v1.SingleArticleReply
	3,  // 20: api.realworld.v1.Article.UnfavoriteArticle:output_type -> api.realworld.v1.SingleArticleReply
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_realworld_v1_article_proto_init() }
func file_realworld_v1_article_proto_init() {
	if File_realworld_v1_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realworld_v1_article_proto_rawDesc), len(file_realworld_v1_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realworld_v1_article_proto_goTypes,
		DependencyIndexes: file_realworld_v1_article_proto_depIdxs,
		MessageInfos:      file_realworld_v1_article_proto_msgTypes,
	}.Build()
	File_realworld_v1_article_proto = out.File
	file_realworld_v1_article_proto_goTypes = nil
	file_realworld_v1_article_proto_depIdxs = nil
}
