// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: realworld/v1/comment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommentRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Comment       *CreateCommentRequest_Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Slug          string                        `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_realworld_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommentRequest) GetComment() *CreateCommentRequest_Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *CreateCommentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateCommentReply struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Comment       *CreateCommentReply_CommentResponse `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReply) Reset() {
	*x = CreateCommentReply{}
	mi := &file_realworld_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReply) ProtoMessage() {}

func (x *CreateCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReply.ProtoReflect.Descriptor instead.
func (*CreateCommentReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentReply) GetComment() *CreateCommentReply_CommentResponse {
	if x != nil {
		return x.Comment
	}
	return nil
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_realworld_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{2}
}

type UpdateCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentReply) Reset() {
	*x = UpdateCommentReply{}
	mi := &file_realworld_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentReply) ProtoMessage() {}

func (x *UpdateCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentReply.ProtoReflect.Descriptor instead.
func (*UpdateCommentReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{3}
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_realworld_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *DeleteCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCommentReply struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Comment       *DeleteCommentReply_CommentResponse `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReply) Reset() {
	*x = DeleteCommentReply{}
	mi := &file_realworld_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReply) ProtoMessage() {}

func (x *DeleteCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReply.ProtoReflect.Descriptor instead.
func (*DeleteCommentReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentReply) GetComment() *DeleteCommentReply_CommentResponse {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRequest) Reset() {
	*x = GetCommentRequest{}
	mi := &file_realworld_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRequest) ProtoMessage() {}

func (x *GetCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetCommentReply struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Comments      []*GetCommentReply_CommentResponse `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Author        *GetCommentReply_ProfileResponse   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentReply) Reset() {
	*x = GetCommentReply{}
	mi := &file_realworld_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentReply) ProtoMessage() {}

func (x *GetCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentReply.ProtoReflect.Descriptor instead.
func (*GetCommentReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommentReply) GetComments() []*GetCommentReply_CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentReply) GetAuthor() *GetCommentReply_ProfileResponse {
	if x != nil {
		return x.Author
	}
	return nil
}

type ListCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentRequest) Reset() {
	*x = ListCommentRequest{}
	mi := &file_realworld_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentRequest) ProtoMessage() {}

func (x *ListCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentRequest.ProtoReflect.Descriptor instead.
func (*ListCommentRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{8}
}

type ListCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentReply) Reset() {
	*x = ListCommentReply{}
	mi := &file_realworld_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentReply) ProtoMessage() {}

func (x *ListCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentReply.ProtoReflect.Descriptor instead.
func (*ListCommentReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{9}
}

type CreateCommentRequest_Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest_Comment) Reset() {
	*x = CreateCommentRequest_Comment{}
	mi := &file_realworld_v1_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest_Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest_Comment) ProtoMessage() {}

func (x *CreateCommentRequest_Comment) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest_Comment.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest_Comment) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateCommentRequest_Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreateCommentReply_ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReply_ProfileResponse) Reset() {
	*x = CreateCommentReply_ProfileResponse{}
	mi := &file_realworld_v1_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReply_ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReply_ProfileResponse) ProtoMessage() {}

func (x *CreateCommentReply_ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReply_ProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentReply_ProfileResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateCommentReply_ProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateCommentReply_ProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateCommentReply_ProfileResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateCommentReply_ProfileResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type CreateCommentReply_CommentResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Id            uint64                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                              `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                              `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Body          string                              `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author        *CreateCommentReply_ProfileResponse `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReply_CommentResponse) Reset() {
	*x = CreateCommentReply_CommentResponse{}
	mi := &file_realworld_v1_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReply_CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReply_CommentResponse) ProtoMessage() {}

func (x *CreateCommentReply_CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReply_CommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentReply_CommentResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CreateCommentReply_CommentResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateCommentReply_CommentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateCommentReply_CommentResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateCommentReply_CommentResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateCommentReply_CommentResponse) GetAuthor() *CreateCommentReply_ProfileResponse {
	if x != nil {
		return x.Author
	}
	return nil
}

type DeleteCommentReply_ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReply_ProfileResponse) Reset() {
	*x = DeleteCommentReply_ProfileResponse{}
	mi := &file_realworld_v1_comment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReply_ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReply_ProfileResponse) ProtoMessage() {}

func (x *DeleteCommentReply_ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReply_ProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentReply_ProfileResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DeleteCommentReply_ProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeleteCommentReply_ProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *DeleteCommentReply_ProfileResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeleteCommentReply_ProfileResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type DeleteCommentReply_CommentResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Id            uint64                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                              `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                              `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Body          string                              `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author        *DeleteCommentReply_ProfileResponse `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReply_CommentResponse) Reset() {
	*x = DeleteCommentReply_CommentResponse{}
	mi := &file_realworld_v1_comment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReply_CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReply_CommentResponse) ProtoMessage() {}

func (x *DeleteCommentReply_CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReply_CommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentReply_CommentResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{5, 1}
}

func (x *DeleteCommentReply_CommentResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCommentReply_CommentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DeleteCommentReply_CommentResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DeleteCommentReply_CommentResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DeleteCommentReply_CommentResponse) GetAuthor() *DeleteCommentReply_ProfileResponse {
	if x != nil {
		return x.Author
	}
	return nil
}

type GetCommentReply_ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentReply_ProfileResponse) Reset() {
	*x = GetCommentReply_ProfileResponse{}
	mi := &file_realworld_v1_comment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentReply_ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentReply_ProfileResponse) ProtoMessage() {}

func (x *GetCommentReply_ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentReply_ProfileResponse.ProtoReflect.Descriptor instead.
func (*GetCommentReply_ProfileResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetCommentReply_ProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetCommentReply_ProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetCommentReply_ProfileResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetCommentReply_ProfileResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type GetCommentReply_CommentResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Id            uint64                           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                           `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                           `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Body          string                           `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author        *GetCommentReply_ProfileResponse `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentReply_CommentResponse) Reset() {
	*x = GetCommentReply_CommentResponse{}
	mi := &file_realworld_v1_comment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentReply_CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentReply_CommentResponse) ProtoMessage() {}

func (x *GetCommentReply_CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_comment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentReply_CommentResponse.ProtoReflect.Descriptor instead.
func (*GetCommentReply_CommentResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_comment_proto_rawDescGZIP(), []int{7, 1}
}

func (x *GetCommentReply_CommentResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCommentReply_CommentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetCommentReply_CommentResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetCommentReply_CommentResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GetCommentReply_CommentResponse) GetAuthor() *GetCommentReply_ProfileResponse {
	if x != nil {
		return x.Author
	}
	return nil
}

var File_realworld_v1_comment_proto protoreflect.FileDescriptor

const file_realworld_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x1arealworld/v1/comment.proto\x12\x10api.realworld.v1\x1a\x1cgoogle/api/annotations.proto\"\x93\x01\n" +
	"\x14CreateCommentRequest\x12H\n" +
	"\acomment\x18\x01 \x01(\v2..api.realworld.v1.CreateCommentRequest.CommentR\acomment\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x1a\x1d\n" +
	"\aComment\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"\x9b\x03\n" +
	"\x12CreateCommentReply\x12N\n" +
	"\acomment\x18\x01 \x01(\v24.api.realworld.v1.CreateCommentReply.CommentResponseR\acomment\x1as\n" +
	"\x0fProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\x1a\xbf\x01\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12L\n" +
	"\x06author\x18\x05 \x01(\v24.api.realworld.v1.CreateCommentReply.ProfileResponseR\x06author\"\x16\n" +
	"\x14UpdateCommentRequest\"\x14\n" +
	"\x12UpdateCommentReply\":\n" +
	"\x14DeleteCommentRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x9b\x03\n" +
	"\x12DeleteCommentReply\x12N\n" +
	"\acomment\x18\x01 \x01(\v24.api.realworld.v1.DeleteCommentReply.CommentResponseR\acomment\x1as\n" +
	"\x0fProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\x1a\xbf\x01\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12L\n" +
	"\x06author\x18\x05 \x01(\v24.api.realworld.v1.DeleteCommentReply.ProfileResponseR\x06author\"'\n" +
	"\x11GetCommentRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xdf\x03\n" +
	"\x0fGetCommentReply\x12M\n" +
	"\bcomments\x18\x01 \x03(\v21.api.realworld.v1.GetCommentReply.CommentResponseR\bcomments\x12I\n" +
	"\x06author\x18\x02 \x01(\v21.api.realworld.v1.GetCommentReply.ProfileResponseR\x06author\x1as\n" +
	"\x0fProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\x1a\xbc\x01\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12I\n" +
	"\x06author\x18\x05 \x01(\v21.api.realworld.v1.GetCommentReply.ProfileResponseR\x06author\"\x14\n" +
	"\x12ListCommentRequest\"\x12\n" +
	"\x10ListCommentReply2\xd4\x04\n" +
	"\aComment\x12\x87\x01\n" +
	"\rCreateComment\x12&.api.realworld.v1.CreateCommentRequest\x1a$.api.realworld.v1.CreateCommentReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/articles/{slug}/comments\x12]\n" +
	"\rUpdateComment\x12&.api.realworld.v1.UpdateCommentRequest\x1a$.api.realworld.v1.UpdateCommentReply\x12\x89\x01\n" +
	"\rDeleteComment\x12&.api.realworld.v1.DeleteCommentRequest\x1a$.api.realworld.v1.DeleteCommentReply\"*\x82\xd3\xe4\x93\x02$*\"/api/articles/{slug}/comments/{id}\x12{\n" +
	"\n" +
	"GetComment\x12#.api.realworld.v1.GetCommentRequest\x1a!.api.realworld.v1.GetCommentReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/articles/{slug}/comments\x12W\n" +
	"\vListComment\x12$.api.realworld.v1.ListCommentRequest\x1a\".api.realworld.v1.ListCommentReplyB&Z$kratos-realworld/api/realworld/v1;v1b\x06proto3"

var (
	file_realworld_v1_comment_proto_rawDescOnce sync.Once
	file_realworld_v1_comment_proto_rawDescData []byte
)

func file_realworld_v1_comment_proto_rawDescGZIP() []byte {
	file_realworld_v1_comment_proto_rawDescOnce.Do(func() {
		file_realworld_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realworld_v1_comment_proto_rawDesc), len(file_realworld_v1_comment_proto_rawDesc)))
	})
	return file_realworld_v1_comment_proto_rawDescData
}

var file_realworld_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_realworld_v1_comment_proto_goTypes = []any{
	(*CreateCommentRequest)(nil),               // 0: api.realworld.v1.CreateCommentRequest
	(*CreateCommentReply)(nil),                 // 1: api.realworld.v1.CreateCommentReply
	(*UpdateCommentRequest)(nil),               // 2: api.realworld.v1.UpdateCommentRequest
	(*UpdateCommentReply)(nil),                 // 3: api.realworld.v1.UpdateCommentReply
	(*DeleteCommentRequest)(nil),               // 4: api.realworld.v1.DeleteCommentRequest
	(*DeleteCommentReply)(nil),                 // 5: api.realworld.v1.DeleteCommentReply
	(*GetCommentRequest)(nil),                  // 6: api.realworld.v1.GetCommentRequest
	(*GetCommentReply)(nil),                    // 7: api.realworld.v1.GetCommentReply
	(*ListCommentRequest)(nil),                 // 8: api.realworld.v1.ListCommentRequest
	(*ListCommentReply)(nil),                   // 9: api.realworld.v1.ListCommentReply
	(*CreateCommentRequest_Comment)(nil),       // 10: api.realworld.v1.CreateCommentRequest.Comment
	(*CreateCommentReply_ProfileResponse)(nil), // 11: api.realworld.v1.CreateCommentReply.ProfileResponse
	(*CreateCommentReply_CommentResponse)(nil), // 12: api.realworld.v1.CreateCommentReply.CommentResponse
	(*DeleteCommentReply_ProfileResponse)(nil), // 13: api.realworld.v1.DeleteCommentReply.ProfileResponse
	(*DeleteCommentReply_CommentResponse)(nil), // 14: api.realworld.v1.DeleteCommentReply.CommentResponse
	(*GetCommentReply_ProfileResponse)(nil),    // 15: api.realworld.v1.GetCommentReply.ProfileResponse
	(*GetCommentReply_CommentResponse)(nil),    // 16: api.realworld.v1.GetCommentReply.CommentResponse
}
var file_realworld_v1_comment_proto_depIdxs = []int32{
	10, // 0: api.realworld.v1.CreateCommentRequest.comment:type_name -> api.realworld.v1.CreateCommentRequest.Comment
	12, // 1: api.realworld.v1.CreateCommentReply.comment:type_name -> api.realworld.v1.CreateCommentReply.CommentResponse
	14, // 2: api.realworld.v1.DeleteCommentReply.comment:type_name -> api.realworld.v1.DeleteCommentReply.CommentResponse
	16, // 3: api.realworld.v1.GetCommentReply.comments:type_name -> api.realworld.v1.GetCommentReply.CommentResponse
	15, // 4: api.realworld.v1.GetCommentReply.author:type_name -> api.realworld.v1.GetCommentReply.ProfileResponse
	11, // 5: api.realworld.v1.CreateCommentReply.CommentResponse.author:type_name -> api.realworld.v1.CreateCommentReply.ProfileResponse
	13, // 6: api.realworld.v1.DeleteCommentReply.CommentResponse.author:type_name -> api.realworld.v1.DeleteCommentReply.ProfileResponse
	15, // 7: api.realworld.v1.GetCommentReply.CommentResponse.author:type_name -> api.realworld.v1.GetCommentReply.ProfileResponse
	0,  // 8: api.realworld.v1.Comment.CreateComment:input_type -> api.realworld.v1.CreateCommentRequest
	2,  // 9: api.realworld.v1.Comment.UpdateComment:input_type -> api.realworld.v1.UpdateCommentRequest
	4,  // 10: api.realworld.v1.Comment.DeleteComment:input_type -> api.realworld.v1.DeleteCommentRequest
	6,  // 11: api.realworld.v1.Comment.GetComment:input_type -> api.realworld.v1.GetCommentRequest
	8,  // 12: api.realworld.v1.Comment.ListComment:input_type -> api.realworld.v1.ListCommentRequest
	1,  // 13: api.realworld.v1.Comment.CreateComment:output_type -> api.realworld.v1.CreateCommentReply
	3,  // 14: api.realworld.v1.Comment.UpdateComment:output_type -> api.realworld.v1.UpdateCommentReply
	5,  // 15: api.realworld.v1.Comment.DeleteComment:output_type -> api.realworld.v1.DeleteCommentReply
	7,  // 16: api.realworld.v1.Comment.GetComment:output_type -> api.realworld.v1.GetCommentReply
	9,  // 17: api.realworld.v1.Comment.ListComment:output_type -> api.realworld.v1.ListCommentReply
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_realworld_v1_comment_proto_init() }
func file_realworld_v1_comment_proto_init() {
	if File_realworld_v1_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realworld_v1_comment_proto_rawDesc), len(file_realworld_v1_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realworld_v1_comment_proto_goTypes,
		DependencyIndexes: file_realworld_v1_comment_proto_depIdxs,
		MessageInfos:      file_realworld_v1_comment_proto_msgTypes,
	}.Build()
	File_realworld_v1_comment_proto = out.File
	file_realworld_v1_comment_proto_goTypes = nil
	file_realworld_v1_comment_proto_depIdxs = nil
}
