// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.0
// source: realworld/v1/profile.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProfileFollowProfile = "/api.realworld.v1.Profile/FollowProfile"
const OperationProfileGetProfile = "/api.realworld.v1.Profile/GetProfile"
const OperationProfileUnfollowProfile = "/api.realworld.v1.Profile/UnfollowProfile"

type ProfileHTTPServer interface {
	// FollowProfile 关注用户
	FollowProfile(context.Context, *FollowProfileRequest) (*ProfileResponse, error)
	// GetProfile 获取用户信息
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileReply, error)
	// UnfollowProfile 取消关注
	UnfollowProfile(context.Context, *UnfollowProfileRequest) (*ProfileResponse, error)
}

func RegisterProfileHTTPServer(s *http.Server, srv ProfileHTTPServer) {
	r := s.Route("/")
	r.GET("/api/profiles/{username}", _Profile_GetProfile0_HTTP_Handler(srv))
	r.POST("/api/profiles/{username}/follow", _Profile_FollowProfile0_HTTP_Handler(srv))
	r.DELETE("/api/profiles/{username}/follow", _Profile_UnfollowProfile0_HTTP_Handler(srv))
}

func _Profile_GetProfile0_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProfileReply)
		return ctx.Result(200, reply)
	}
}

func _Profile_FollowProfile0_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FollowProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileFollowProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FollowProfile(ctx, req.(*FollowProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _Profile_UnfollowProfile0_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnfollowProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileUnfollowProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnfollowProfile(ctx, req.(*UnfollowProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

type ProfileHTTPClient interface {
	// FollowProfile 关注用户
	FollowProfile(ctx context.Context, req *FollowProfileRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	// GetProfile 获取用户信息
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *GetProfileReply, err error)
	// UnfollowProfile 取消关注
	UnfollowProfile(ctx context.Context, req *UnfollowProfileRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
}

type ProfileHTTPClientImpl struct {
	cc *http.Client
}

func NewProfileHTTPClient(client *http.Client) ProfileHTTPClient {
	return &ProfileHTTPClientImpl{client}
}

// FollowProfile 关注用户
func (c *ProfileHTTPClientImpl) FollowProfile(ctx context.Context, in *FollowProfileRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/profiles/{username}/follow"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileFollowProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetProfile 获取用户信息
func (c *ProfileHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*GetProfileReply, error) {
	var out GetProfileReply
	pattern := "/api/profiles/{username}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileGetProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnfollowProfile 取消关注
func (c *ProfileHTTPClientImpl) UnfollowProfile(ctx context.Context, in *UnfollowProfileRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/profiles/{username}/follow"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileUnfollowProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
