// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: realworld/v1/profile.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnfollowProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowProfileRequest) Reset() {
	*x = UnfollowProfileRequest{}
	mi := &file_realworld_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowProfileRequest) ProtoMessage() {}

func (x *UnfollowProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowProfileRequest.ProtoReflect.Descriptor instead.
func (*UnfollowProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *UnfollowProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FollowProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowProfileRequest) Reset() {
	*x = FollowProfileRequest{}
	mi := &file_realworld_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowProfileRequest) ProtoMessage() {}

func (x *FollowProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowProfileRequest.ProtoReflect.Descriptor instead.
func (*FollowProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *FollowProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_realworld_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProfileResponse) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_realworld_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{3}
}

type CreateProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileReply) Reset() {
	*x = CreateProfileReply{}
	mi := &file_realworld_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileReply) ProtoMessage() {}

func (x *CreateProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileReply.ProtoReflect.Descriptor instead.
func (*CreateProfileReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{4}
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_realworld_v1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{5}
}

type UpdateProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReply) Reset() {
	*x = UpdateProfileReply{}
	mi := &file_realworld_v1_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReply) ProtoMessage() {}

func (x *UpdateProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReply.ProtoReflect.Descriptor instead.
func (*UpdateProfileReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{6}
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_realworld_v1_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{7}
}

type DeleteProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileReply) Reset() {
	*x = DeleteProfileReply{}
	mi := &file_realworld_v1_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileReply) ProtoMessage() {}

func (x *DeleteProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileReply.ProtoReflect.Descriptor instead.
func (*DeleteProfileReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{8}
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_realworld_v1_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{9}
}

func (x *GetProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReply) Reset() {
	*x = GetProfileReply{}
	mi := &file_realworld_v1_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReply) ProtoMessage() {}

func (x *GetProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReply.ProtoReflect.Descriptor instead.
func (*GetProfileReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{10}
}

type ListProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfileRequest) Reset() {
	*x = ListProfileRequest{}
	mi := &file_realworld_v1_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfileRequest) ProtoMessage() {}

func (x *ListProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfileRequest.ProtoReflect.Descriptor instead.
func (*ListProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{11}
}

type ListProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfileReply) Reset() {
	*x = ListProfileReply{}
	mi := &file_realworld_v1_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfileReply) ProtoMessage() {}

func (x *ListProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfileReply.ProtoReflect.Descriptor instead.
func (*ListProfileReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_profile_proto_rawDescGZIP(), []int{12}
}

var File_realworld_v1_profile_proto protoreflect.FileDescriptor

const file_realworld_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x1arealworld/v1/profile.proto\x12\x10api.realworld.v1\x1a\x1cgoogle/api/annotations.proto\"4\n" +
	"\x16UnfollowProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"2\n" +
	"\x14FollowProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"s\n" +
	"\x0fProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\"\x16\n" +
	"\x14CreateProfileRequest\"\x14\n" +
	"\x12CreateProfileReply\"\x16\n" +
	"\x14UpdateProfileRequest\"\x14\n" +
	"\x12UpdateProfileReply\"\x16\n" +
	"\x14DeleteProfileRequest\"\x14\n" +
	"\x12DeleteProfileReply\"/\n" +
	"\x11GetProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x11\n" +
	"\x0fGetProfileReply\"\x14\n" +
	"\x12ListProfileRequest\"\x12\n" +
	"\x10ListProfileReply2\x8a\x06\n" +
	"\aProfile\x12]\n" +
	"\rCreateProfile\x12&.api.realworld.v1.CreateProfileRequest\x1a$.api.realworld.v1.CreateProfileReply\x12]\n" +
	"\rUpdateProfile\x12&.api.realworld.v1.UpdateProfileRequest\x1a$.api.realworld.v1.UpdateProfileReply\x12]\n" +
	"\rDeleteProfile\x12&.api.realworld.v1.DeleteProfileRequest\x1a$.api.realworld.v1.DeleteProfileReply\x12v\n" +
	"\n" +
	"GetProfile\x12#.api.realworld.v1.GetProfileRequest\x1a!.api.realworld.v1.GetProfileReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/profiles/{username}\x12W\n" +
	"\vListProfile\x12$.api.realworld.v1.ListProfileRequest\x1a\".api.realworld.v1.ListProfileReply\x12\x86\x01\n" +
	"\rFollowProfile\x12&.api.realworld.v1.FollowProfileRequest\x1a!.api.realworld.v1.ProfileResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/profiles/{username}/follow\x12\x87\x01\n" +
	"\x0fUnfollowProfile\x12(.api.realworld.v1.UnfollowProfileRequest\x1a!.api.realworld.v1.ProfileResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/api/profiles/{username}/followB&Z$kratos-realworld/api/realworld/v1;v1b\x06proto3"

var (
	file_realworld_v1_profile_proto_rawDescOnce sync.Once
	file_realworld_v1_profile_proto_rawDescData []byte
)

func file_realworld_v1_profile_proto_rawDescGZIP() []byte {
	file_realworld_v1_profile_proto_rawDescOnce.Do(func() {
		file_realworld_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realworld_v1_profile_proto_rawDesc), len(file_realworld_v1_profile_proto_rawDesc)))
	})
	return file_realworld_v1_profile_proto_rawDescData
}

var file_realworld_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_realworld_v1_profile_proto_goTypes = []any{
	(*UnfollowProfileRequest)(nil), // 0: api.realworld.v1.UnfollowProfileRequest
	(*FollowProfileRequest)(nil),   // 1: api.realworld.v1.FollowProfileRequest
	(*ProfileResponse)(nil),        // 2: api.realworld.v1.ProfileResponse
	(*CreateProfileRequest)(nil),   // 3: api.realworld.v1.CreateProfileRequest
	(*CreateProfileReply)(nil),     // 4: api.realworld.v1.CreateProfileReply
	(*UpdateProfileRequest)(nil),   // 5: api.realworld.v1.UpdateProfileRequest
	(*UpdateProfileReply)(nil),     // 6: api.realworld.v1.UpdateProfileReply
	(*DeleteProfileRequest)(nil),   // 7: api.realworld.v1.DeleteProfileRequest
	(*DeleteProfileReply)(nil),     // 8: api.realworld.v1.DeleteProfileReply
	(*GetProfileRequest)(nil),      // 9: api.realworld.v1.GetProfileRequest
	(*GetProfileReply)(nil),        // 10: api.realworld.v1.GetProfileReply
	(*ListProfileRequest)(nil),     // 11: api.realworld.v1.ListProfileRequest
	(*ListProfileReply)(nil),       // 12: api.realworld.v1.ListProfileReply
}
var file_realworld_v1_profile_proto_depIdxs = []int32{
	3,  // 0: api.realworld.v1.Profile.CreateProfile:input_type -> api.realworld.v1.CreateProfileRequest
	5,  // 1: api.realworld.v1.Profile.UpdateProfile:input_type -> api.realworld.v1.UpdateProfileRequest
	7,  // 2: api.realworld.v1.Profile.DeleteProfile:input_type -> api.realworld.v1.DeleteProfileRequest
	9,  // 3: api.realworld.v1.Profile.GetProfile:input_type -> api.realworld.v1.GetProfileRequest
	11, // 4: api.realworld.v1.Profile.ListProfile:input_type -> api.realworld.v1.ListProfileRequest
	1,  // 5: api.realworld.v1.Profile.FollowProfile:input_type -> api.realworld.v1.FollowProfileRequest
	0,  // 6: api.realworld.v1.Profile.UnfollowProfile:input_type -> api.realworld.v1.UnfollowProfileRequest
	4,  // 7: api.realworld.v1.Profile.CreateProfile:output_type -> api.realworld.v1.CreateProfileReply
	6,  // 8: api.realworld.v1.Profile.UpdateProfile:output_type -> api.realworld.v1.UpdateProfileReply
	8,  // 9: api.realworld.v1.Profile.DeleteProfile:output_type -> api.realworld.v1.DeleteProfileReply
	10, // 10: api.realworld.v1.Profile.GetProfile:output_type -> api.realworld.v1.GetProfileReply
	12, // 11: api.realworld.v1.Profile.ListProfile:output_type -> api.realworld.v1.ListProfileReply
	2,  // 12: api.realworld.v1.Profile.FollowProfile:output_type -> api.realworld.v1.ProfileResponse
	2,  // 13: api.realworld.v1.Profile.UnfollowProfile:output_type -> api.realworld.v1.ProfileResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_realworld_v1_profile_proto_init() }
func file_realworld_v1_profile_proto_init() {
	if File_realworld_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realworld_v1_profile_proto_rawDesc), len(file_realworld_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realworld_v1_profile_proto_goTypes,
		DependencyIndexes: file_realworld_v1_profile_proto_depIdxs,
		MessageInfos:      file_realworld_v1_profile_proto_msgTypes,
	}.Build()
	File_realworld_v1_profile_proto = out.File
	file_realworld_v1_profile_proto_goTypes = nil
	file_realworld_v1_profile_proto_depIdxs = nil
}
