syntax = "proto3";

package realworld.v1;

import "google/api/annotations.proto";

option go_package = "realworld/api/realworld/v1;v1";

// RealWorld
service RealWorld {
  // 登录
  rpc Login(LoginRequest) returns (LoginResponse) {
    option (google.api.http) = {
      post: "/api/users/login/123",
      body: "*",
    };
  };
}

message LoginRequest {
  message User {
    string email    = 1;
    string password = 2;
  }
  User user = 1;
}

message LoginResponse {
  message User {
    string username = 1;
    string email    = 2;
    string password = 3;
    string bio      = 4;
    string image    = 5;
  }
  User user = 1;
}