// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: realworld/v1/tag.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_realworld_v1_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{0}
}

type CreateTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagReply) Reset() {
	*x = CreateTagReply{}
	mi := &file_realworld_v1_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagReply) ProtoMessage() {}

func (x *CreateTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagReply.ProtoReflect.Descriptor instead.
func (*CreateTagReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{1}
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_realworld_v1_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{2}
}

type UpdateTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagReply) Reset() {
	*x = UpdateTagReply{}
	mi := &file_realworld_v1_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagReply) ProtoMessage() {}

func (x *UpdateTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagReply.ProtoReflect.Descriptor instead.
func (*UpdateTagReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{3}
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_realworld_v1_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{4}
}

type DeleteTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagReply) Reset() {
	*x = DeleteTagReply{}
	mi := &file_realworld_v1_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagReply) ProtoMessage() {}

func (x *DeleteTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagReply.ProtoReflect.Descriptor instead.
func (*DeleteTagReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{5}
}

type GetTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagRequest) Reset() {
	*x = GetTagRequest{}
	mi := &file_realworld_v1_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRequest) ProtoMessage() {}

func (x *GetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRequest.ProtoReflect.Descriptor instead.
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{6}
}

type GetTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagReply) Reset() {
	*x = GetTagReply{}
	mi := &file_realworld_v1_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagReply) ProtoMessage() {}

func (x *GetTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagReply.ProtoReflect.Descriptor instead.
func (*GetTagReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{7}
}

type ListTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagRequest) Reset() {
	*x = ListTagRequest{}
	mi := &file_realworld_v1_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagRequest) ProtoMessage() {}

func (x *ListTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagRequest.ProtoReflect.Descriptor instead.
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{8}
}

type ListTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagReply) Reset() {
	*x = ListTagReply{}
	mi := &file_realworld_v1_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagReply) ProtoMessage() {}

func (x *ListTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagReply.ProtoReflect.Descriptor instead.
func (*ListTagReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_tag_proto_rawDescGZIP(), []int{9}
}

func (x *ListTagReply) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_realworld_v1_tag_proto protoreflect.FileDescriptor

const file_realworld_v1_tag_proto_rawDesc = "" +
	"\n" +
	"\x16realworld/v1/tag.proto\x12\x10api.realworld.v1\x1a\x1cgoogle/api/annotations.proto\"\x12\n" +
	"\x10CreateTagRequest\"\x10\n" +
	"\x0eCreateTagReply\"\x12\n" +
	"\x10UpdateTagRequest\"\x10\n" +
	"\x0eUpdateTagReply\"\x12\n" +
	"\x10DeleteTagRequest\"\x10\n" +
	"\x0eDeleteTagReply\"\x0f\n" +
	"\rGetTagRequest\"\r\n" +
	"\vGetTagReply\"\x10\n" +
	"\x0eListTagRequest\"\"\n" +
	"\fListTagReply\x12\x12\n" +
	"\x04Tags\x18\x01 \x03(\tR\x04Tags2\xa8\x03\n" +
	"\x03Tag\x12Q\n" +
	"\tCreateTag\x12\".api.realworld.v1.CreateTagRequest\x1a .api.realworld.v1.CreateTagReply\x12Q\n" +
	"\tUpdateTag\x12\".api.realworld.v1.UpdateTagRequest\x1a .api.realworld.v1.UpdateTagReply\x12Q\n" +
	"\tDeleteTag\x12\".api.realworld.v1.DeleteTagRequest\x1a .api.realworld.v1.DeleteTagReply\x12H\n" +
	"\x06GetTag\x12\x1f.api.realworld.v1.GetTagRequest\x1a\x1d.api.realworld.v1.GetTagReply\x12^\n" +
	"\aListTag\x12 .api.realworld.v1.ListTagRequest\x1a\x1e.api.realworld.v1.ListTagReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/tagsB&Z$kratos-realworld/api/realworld/v1;v1b\x06proto3"

var (
	file_realworld_v1_tag_proto_rawDescOnce sync.Once
	file_realworld_v1_tag_proto_rawDescData []byte
)

func file_realworld_v1_tag_proto_rawDescGZIP() []byte {
	file_realworld_v1_tag_proto_rawDescOnce.Do(func() {
		file_realworld_v1_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realworld_v1_tag_proto_rawDesc), len(file_realworld_v1_tag_proto_rawDesc)))
	})
	return file_realworld_v1_tag_proto_rawDescData
}

var file_realworld_v1_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_realworld_v1_tag_proto_goTypes = []any{
	(*CreateTagRequest)(nil), // 0: api.realworld.v1.CreateTagRequest
	(*CreateTagReply)(nil),   // 1: api.realworld.v1.CreateTagReply
	(*UpdateTagRequest)(nil), // 2: api.realworld.v1.UpdateTagRequest
	(*UpdateTagReply)(nil),   // 3: api.realworld.v1.UpdateTagReply
	(*DeleteTagRequest)(nil), // 4: api.realworld.v1.DeleteTagRequest
	(*DeleteTagReply)(nil),   // 5: api.realworld.v1.DeleteTagReply
	(*GetTagRequest)(nil),    // 6: api.realworld.v1.GetTagRequest
	(*GetTagReply)(nil),      // 7: api.realworld.v1.GetTagReply
	(*ListTagRequest)(nil),   // 8: api.realworld.v1.ListTagRequest
	(*ListTagReply)(nil),     // 9: api.realworld.v1.ListTagReply
}
var file_realworld_v1_tag_proto_depIdxs = []int32{
	0, // 0: api.realworld.v1.Tag.CreateTag:input_type -> api.realworld.v1.CreateTagRequest
	2, // 1: api.realworld.v1.Tag.UpdateTag:input_type -> api.realworld.v1.UpdateTagRequest
	4, // 2: api.realworld.v1.Tag.DeleteTag:input_type -> api.realworld.v1.DeleteTagRequest
	6, // 3: api.realworld.v1.Tag.GetTag:input_type -> api.realworld.v1.GetTagRequest
	8, // 4: api.realworld.v1.Tag.ListTag:input_type -> api.realworld.v1.ListTagRequest
	1, // 5: api.realworld.v1.Tag.CreateTag:output_type -> api.realworld.v1.CreateTagReply
	3, // 6: api.realworld.v1.Tag.UpdateTag:output_type -> api.realworld.v1.UpdateTagReply
	5, // 7: api.realworld.v1.Tag.DeleteTag:output_type -> api.realworld.v1.DeleteTagReply
	7, // 8: api.realworld.v1.Tag.GetTag:output_type -> api.realworld.v1.GetTagReply
	9, // 9: api.realworld.v1.Tag.ListTag:output_type -> api.realworld.v1.ListTagReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_realworld_v1_tag_proto_init() }
func file_realworld_v1_tag_proto_init() {
	if File_realworld_v1_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realworld_v1_tag_proto_rawDesc), len(file_realworld_v1_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realworld_v1_tag_proto_goTypes,
		DependencyIndexes: file_realworld_v1_tag_proto_depIdxs,
		MessageInfos:      file_realworld_v1_tag_proto_msgTypes,
	}.Build()
	File_realworld_v1_tag_proto = out.File
	file_realworld_v1_tag_proto_goTypes = nil
	file_realworld_v1_tag_proto_depIdxs = nil
}
