// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/helloworld/v1/student.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 这里的 HelloReq 和 HelloResp
type HelloReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Sayname       string                 `protobuf:"bytes,3,opt,name=sayname,proto3" json:"sayname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HelloReq) GetSayname() string {
	if x != nil {
		return x.Sayname
	}
	return ""
}

type HelloResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{2}
}

type CreateStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentReply) Reset() {
	*x = CreateStudentReply{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentReply) ProtoMessage() {}

func (x *CreateStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentReply.ProtoReflect.Descriptor instead.
func (*CreateStudentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{3}
}

type UpdateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentRequest) Reset() {
	*x = UpdateStudentRequest{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentRequest) ProtoMessage() {}

func (x *UpdateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{4}
}

type UpdateStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentReply) Reset() {
	*x = UpdateStudentReply{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentReply) ProtoMessage() {}

func (x *UpdateStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentReply.ProtoReflect.Descriptor instead.
func (*UpdateStudentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{5}
}

type DeleteStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentRequest) Reset() {
	*x = DeleteStudentRequest{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentRequest) ProtoMessage() {}

func (x *DeleteStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{6}
}

type DeleteStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentReply) Reset() {
	*x = DeleteStudentReply{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentReply) ProtoMessage() {}

func (x *DeleteStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentReply.ProtoReflect.Descriptor instead.
func (*DeleteStudentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{7}
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{8}
}

type GetStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentReply) Reset() {
	*x = GetStudentReply{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentReply) ProtoMessage() {}

func (x *GetStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentReply.ProtoReflect.Descriptor instead.
func (*GetStudentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{9}
}

type ListStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentRequest) Reset() {
	*x = ListStudentRequest{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentRequest) ProtoMessage() {}

func (x *ListStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentRequest.ProtoReflect.Descriptor instead.
func (*ListStudentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{10}
}

type ListStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentReply) Reset() {
	*x = ListStudentReply{}
	mi := &file_api_helloworld_v1_student_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentReply) ProtoMessage() {}

func (x *ListStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_student_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentReply.ProtoReflect.Descriptor instead.
func (*ListStudentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_student_proto_rawDescGZIP(), []int{11}
}

var File_api_helloworld_v1_student_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_student_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/student.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"H\n" +
	"\bHelloReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\asayname\x18\x03 \x01(\tR\asayname\"9\n" +
	"\tHelloResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x16\n" +
	"\x14CreateStudentRequest\"\x14\n" +
	"\x12CreateStudentReply\"\x16\n" +
	"\x14UpdateStudentRequest\"\x14\n" +
	"\x12UpdateStudentReply\"\x16\n" +
	"\x14DeleteStudentRequest\"\x14\n" +
	"\x12DeleteStudentReply\"\x13\n" +
	"\x11GetStudentRequest\"\x11\n" +
	"\x0fGetStudentReply\"\x14\n" +
	"\x12ListStudentRequest\"\x12\n" +
	"\x10ListStudentReply2\xdf\x04\n" +
	"\aStudent\x12~\n" +
	"\x05Hello\x12\x1b.api.helloworld.v1.HelloReq\x1a\x1c.api.helloworld.v1.HelloResp\":\x82\xd3\xe4\x93\x024Z#:\x01*\"\x1e/hello/{id}/sayhello/{sayname}\x12\r/hello/{name}\x12_\n" +
	"\rCreateStudent\x12'.api.helloworld.v1.CreateStudentRequest\x1a%.api.helloworld.v1.CreateStudentReply\x12_\n" +
	"\rUpdateStudent\x12'.api.helloworld.v1.UpdateStudentRequest\x1a%.api.helloworld.v1.UpdateStudentReply\x12_\n" +
	"\rDeleteStudent\x12'.api.helloworld.v1.DeleteStudentRequest\x1a%.api.helloworld.v1.DeleteStudentReply\x12V\n" +
	"\n" +
	"GetStudent\x12$.api.helloworld.v1.GetStudentRequest\x1a\".api.helloworld.v1.GetStudentReply\x12Y\n" +
	"\vListStudent\x12%.api.helloworld.v1.ListStudentRequest\x1a#.api.helloworld.v1.ListStudentReplyB6\n" +
	"\x11api.helloworld.v1P\x01Z\x1fhelloworld/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_student_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_student_proto_rawDescData []byte
)

func file_api_helloworld_v1_student_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_student_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_student_proto_rawDesc), len(file_api_helloworld_v1_student_proto_rawDesc)))
	})
	return file_api_helloworld_v1_student_proto_rawDescData
}

var file_api_helloworld_v1_student_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_helloworld_v1_student_proto_goTypes = []any{
	(*HelloReq)(nil),             // 0: api.helloworld.v1.HelloReq
	(*HelloResp)(nil),            // 1: api.helloworld.v1.HelloResp
	(*CreateStudentRequest)(nil), // 2: api.helloworld.v1.CreateStudentRequest
	(*CreateStudentReply)(nil),   // 3: api.helloworld.v1.CreateStudentReply
	(*UpdateStudentRequest)(nil), // 4: api.helloworld.v1.UpdateStudentRequest
	(*UpdateStudentReply)(nil),   // 5: api.helloworld.v1.UpdateStudentReply
	(*DeleteStudentRequest)(nil), // 6: api.helloworld.v1.DeleteStudentRequest
	(*DeleteStudentReply)(nil),   // 7: api.helloworld.v1.DeleteStudentReply
	(*GetStudentRequest)(nil),    // 8: api.helloworld.v1.GetStudentRequest
	(*GetStudentReply)(nil),      // 9: api.helloworld.v1.GetStudentReply
	(*ListStudentRequest)(nil),   // 10: api.helloworld.v1.ListStudentRequest
	(*ListStudentReply)(nil),     // 11: api.helloworld.v1.ListStudentReply
}
var file_api_helloworld_v1_student_proto_depIdxs = []int32{
	0,  // 0: api.helloworld.v1.Student.Hello:input_type -> api.helloworld.v1.HelloReq
	2,  // 1: api.helloworld.v1.Student.CreateStudent:input_type -> api.helloworld.v1.CreateStudentRequest
	4,  // 2: api.helloworld.v1.Student.UpdateStudent:input_type -> api.helloworld.v1.UpdateStudentRequest
	6,  // 3: api.helloworld.v1.Student.DeleteStudent:input_type -> api.helloworld.v1.DeleteStudentRequest
	8,  // 4: api.helloworld.v1.Student.GetStudent:input_type -> api.helloworld.v1.GetStudentRequest
	10, // 5: api.helloworld.v1.Student.ListStudent:input_type -> api.helloworld.v1.ListStudentRequest
	1,  // 6: api.helloworld.v1.Student.Hello:output_type -> api.helloworld.v1.HelloResp
	3,  // 7: api.helloworld.v1.Student.CreateStudent:output_type -> api.helloworld.v1.CreateStudentReply
	5,  // 8: api.helloworld.v1.Student.UpdateStudent:output_type -> api.helloworld.v1.UpdateStudentReply
	7,  // 9: api.helloworld.v1.Student.DeleteStudent:output_type -> api.helloworld.v1.DeleteStudentReply
	9,  // 10: api.helloworld.v1.Student.GetStudent:output_type -> api.helloworld.v1.GetStudentReply
	11, // 11: api.helloworld.v1.Student.ListStudent:output_type -> api.helloworld.v1.ListStudentReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_student_proto_init() }
func file_api_helloworld_v1_student_proto_init() {
	if File_api_helloworld_v1_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_student_proto_rawDesc), len(file_api_helloworld_v1_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_student_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_student_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_student_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_student_proto = out.File
	file_api_helloworld_v1_student_proto_goTypes = nil
	file_api_helloworld_v1_student_proto_depIdxs = nil
}
